### ISSUE TITLE
error Operation not permitted elastizabbix-cluster.lock

### ISSUE THREAD

**Issue by ribbles** [mkhpalm/elastizabbix#18]
Get the following error:

`Received value [Traceback (most recent call last): File "/usr/lib/zabbix/externalscripts/elastizabbix", line 88, in <module> stat = get_stat(api, stat) File "/usr/lib/zabbix/externalscripts/elastizabbix", line 55, in get_stat d = get_cache(api) File "/usr/lib/zabbix/externalscripts/elastizabbix", line 45, in get_cache os.remove(lock)OSError: [Errno 1] Operation not permitted: '/tmp/elastizabbix-cluster.lock'] is not suitable for value type [Numeric (unsigned)] and data type [Decimal]`

**Comment by ribbles** [comment]
testing as root created file that zabbix had no permission to touch.
