### ISSUE TITLE
No JSON object could be decoded

### ISSUE THREAD

**Issue by peske** [mkhpalm/elastizabbix#2]
It looks that elastizabbix script does not work? Here's what I'm getting when trying to execute it manually:

```
root@IT-ES01:~# /etc/zabbix/externalscripts/elastizabbix health status
Traceback (most recent call last):
  File "/etc/zabbix/externalscripts/elastizabbix", line 63, in <module>
    stat = get_stat(api, stat)
  File "/etc/zabbix/externalscripts/elastizabbix", line 31, in get_stat
    d = get_cache(api)
  File "/etc/zabbix/externalscripts/elastizabbix", line 28, in get_cache
    return json.load(open(cache))
  File "/usr/lib/python2.7/json/__init__.py", line 290, in load
    **kw)
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
root@IT-ES01:~#
```

**Comment by peske** [comment]
I've just discovered something that may help you understand what is happening. All cache files in /tmp directory contain line:

```
No handler found for uri [http://localhost:9200/_cluster/health] and method [GET]
```

I've tried cURL, and I'm getting JSON:

```
root@IT-ES01:~# curl http://localhost:9200/_cluster/health
{"cluster_name":"IT-ES","status":"green","timed_out":false,"number_of_nodes":2,"number_of_data_nodes":2,"active_primary_shards":1,"active_shards":2,"relocating_shards":0,"initializing_shards":0,"unassigned_shards":0,"delayed_unassigned_shards":0,"number_of_pending_tasks":0,"number_of_in_flight_fetch":0,"task_max_waiting_in_queue_millis":0,"active_shards_percent_as_number":100.0}
```

Any ideas?

Thanks!

**Comment by peske** [comment]
Me again, sorry... More info: it looks that it is not about your script, but python urllib. I've created simple snippet:

```
#!/usr/bin/python
import os
import sys
import json
import urllib
import time

the_file = '/tmp/thefile.json'
urllib.urlretrieve('http://localhost:9200/_nodes/stats', the_file)
```

And again I've got the same "No handler..."

How to _repair_ python?

Thanks!

**Comment by peske** [comment]
Guess what? Me again :)

I'm not sure why, but with urllib and httplib I'm getting "No handler..."

But surprisingly enough, urllib2 works like a charm:

```
r = urllib2.urlopen('http://localhost:9200/_nodes/stats')
print r.read()
```

These are literally my first lines of python code :) Will you jump-in to help?

**Comment by peske** [comment]
Well, it looks that I've gone from the first python line to the first successful script in few hours :-)

So, as I've already mentioned in my case only urllib2 works, so I've changed line 5:

```
import urllib2
```

instead of

```
import urllib
```

And also changed line 23 to:

```
with open(cache, 'w') as f: f.write(urllib2.urlopen(stats[api]).read())
```

instead of:

```
urllib.urlretrieve(stats[api], cache)
```

And now everything works here. 

I won't bother you any more.

**Comment by mkhpalm** [comment]
Thanks! Works for me.
